### ISSUE TITLE
Missing ast.unparse method in Python 3.8

### ISSUE THREAD

**Issue by DuanYaQi** [FlagOpen/FlagGems#109]
# Issue

**In Python 3.8, the `ast` module does not include the `unparse` method.**

While requires-python = ">=3.8" given

# Env
Python 3.8.18
Torch: 2.3.1
Triton: 2.3.1
Pytest: 8.2.2

# command

```
python -m pytest -svvv tests/test_unary_pointwise_ops.py::test_accuracy_abs
```

# Result

![image](https://github.com/FlagOpen/FlagGems/assets/30496905/397c16c0-4ec1-4287-a165-ef36c8674705)

![image](https://github.com/FlagOpen/FlagGems/assets/30496905/531753d1-e5b0-4e12-bc31-ce9c9ec0219b)

**Comment by iclementine** [comment]
In this PR #98, we changed the method to inline a jitted-function. Now it can be *called* in another jitted function. So we nolonger need `ast.unparse`.

**Comment by DuanYaQi** [comment]
> In this PR #98, we changed the method to inline a jitted-function. Now it can be _called_ in another jitted function. So we nolonger need `ast.unparse`.

got it! thx for your reply
