### ISSUE TITLE
error with op triu

### ISSUE THREAD

**Issue by tianxiao-baai** [FlagOpen/FlagGems#122]
error with op triu，message error as follows:
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/e1e0173a-5549-4081-bfb3-e7eae4aa6a77">

**Comment by iclementine** [comment]
It is the problem that the max memory offset used to index the tensor exceeds the maximum value of int32. I am fixing it with int64 indexing when needed.

**Comment by tianxiao-baai** [comment]
The new code no longer reports any errors, so close this issue.
