### ISSUE TITLE
error with op amax

### ISSUE THREAD

**Issue by tianxiao-baai** [FlagOpen/FlagGems#123]
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/f93d8d2b-a631-4a19-b9ac-44b23e0a602d">

**Comment by iclementine** [comment]
It is the problem that the max memory offset used to index the tensor exceeds the maximum value of int32. I am fixing it with int64 indexing when needed.

**Comment by tianxiao-baai** [comment]
The new code no longer reports any errors, so close this issue.
