### ISSUE TITLE
flaggems@baai.ac.cn 邮箱异常

### ISSUE THREAD

**Issue by JT-Ushio** [FlagOpen/FlagGems#137]
您好，flaggems@baai.ac.cn的邮箱发信提示`SMTP error, RCPT TO: Host baai.ac.cn(106.11.226.174) RCPT TO said 554 RCPT ([flaggems@baai.ac.cn](mailto:flaggems@baai.ac.cn)) dosn't exist`

或者是否方便提供陈飞宇工程师的联系方式呢？想联系他要一下Triton中国生态Meetup《Triton语言入门教程》的PPT，非常感谢！

**Comment by StrongSpoon** [comment]
Sorry for the error. We'll fix it soon.
Feiyu's email address is fychen@baai.ac.cn. And the website of triton tutorial slides is https://baai.org/l/FHcyY. Thanks for your attention to our community~

**Comment by StrongSpoon** [comment]
We have fixed the error of email address.

**Comment by JT-Ushio** [comment]
Thanks a lot, my issue has been perfectly resolved.
