### ISSUE TITLE
[BUG] operators' names are mismatched

### ISSUE THREAD

**Issue by shh2000** [FlagOpen/FlagGems#147]
Hello, the names of the operators listed in https://github.com/FlagOpen/FlagGems/blob/master/OperatorList.md may have slight differences from the actual operator names used in kernel development or CI testing. For example, there is groupnorm@CI while group_norm@OperatorList.md. I suggest to fix the name in OperatorList.md.

**Comment by StrongSpoon** [comment]
thanks for your advice. we'll work on that.
