### ISSUE TITLE
[Feature] removing the version restrictions for torch and triton

### ISSUE THREAD

**Issue by zhyncs** [FlagOpen/FlagGems#160]
Hi all. Some PyPI torch versions, like 2.4, conflict with FlagGems. Removing the version restriction on FlagGems would solve this issue. May we consider removing the version restrictions for torch and triton? Thanks.

ref

https://github.com/FlagOpen/FlagGems/blob/4f6ea4cc2fc004d806d48a7d8f21dcb6a79a6dc5/pyproject.toml#L20-L21

**Comment by StrongSpoon** [comment]
Since FlagGems only supports triton after 2.2.0, removing restriction of triton might not be possible. We will try on torch2.4 and figure out why they conflict.

**Comment by zhyncs** [comment]
Torch 2.4 use triton 3.0.0
