### ISSUE TITLE
Dropout Test Error Between CUDA and CPU

### ISSUE THREAD

**Issue by DuanYaQi** [FlagOpen/FlagGems#161]
In the README.md test method, I encountered a **dropout** test failure with the parameters `shape = (1024, 1024), p = 0.3, dtype = torch.float16.`

```
python -m pytest -sv tests/test_special_ops.py::test_accuracy_dropout'[dtype0-0.3-shape0]' --device cpu
```

FlagGems Commit: 2e55d66
Python 3.10.12
Torch: 2.3.1
Triton: 2.3.1
Pytest: 8.2.2

**Comment by DuanYaQi** [comment]
If the dropout(random-like) op can't compare results between CUDA and CPU, we might need to add some code hints.

**Comment by StrongSpoon** [comment]
According to this issue [Different Dropout Result on CPU and GPU with Manual Seed](https://github.com/pytorch/pytorch/issues/2976), CPU and GPU use different RNG, leading to different results between reference and result. We will apply a special method for this situation.

**Comment by DuanYaQi** [comment]
What’s intriguing is that this issue does not happen with FP32 input.
