### ISSUE TITLE
SomeQuestions

### ISSUE THREAD

**Issue by gavin838** [FlagOpen/FlagGems#176]
1.FlagGems后期是作为一个单独的仓库还是会在某个时间点把算子库合到Triton社区，随Triton社区一起维护么？
2.假如作为一个单独仓库独立演进，Triton后面若有大的版本更新，当前的一些表达、用法不再支持，FlagGems怎么解决？
3.若后期由于某些政治或其他不可抗力因素，Triton不再完全开源，此时又如何解决？
感谢解答！

**Comment by tongxin** [comment]
谢谢关注，这些问题很好，我只能讲讲目前的考虑。
1. FlagGems是用Triton开发的算子库，Triton-lang我们看到只包括语言前端、编译器和一部分样例实现，我们开发FlagGems是为了弥补Pytorch eager模式使用Triton的便捷性，项目中涉及到Triton本身的特性改变是可以考虑upstream到Triton社区的。
2. 会随着Triton持续更新。
3. 根据需要和实际情况决定是否继续维护独立的Triton实现。
