### ISSUE TITLE
Code Contribution: 【Lv2】【Operator Development】count_nonzero

### ISSUE THREAD

**Issue by Tango2018cc** [FlagOpen/FlagGems#255]
将以下算子贡献至https://github.com/FlagOpen/FlagGems/tree/master/src/flag_gems/ops 目录下

count_nonzero

认领方式：
1. Issue中留言评论：「认领人名称+认领」
2. 在贡献者微信群内发送：认领的Issue号例如：「认领+[https://github.com/FlagOpen/FlagGems/issues/xxx]」

**Comment by BeingGod** [comment]
BeingGod 认领

**Comment by Tango2018cc** [comment]
DDL to 11.15-22

**Comment by BeingGod** [comment]
ACK

**Comment by shuailong616** [comment]
shuailong616 已认领
