### ISSUE TITLE
[Tags: v2.1] Error behaviorfor 'flag_gems.masked_fill(inp, mask, value)'

### ISSUE THREAD

**Issue by Dayrker** [FlagOpen/FlagGems#266]
### Describe the bug

位置：
FlagGems/tests/test_unary_pointwise_ops.py::test_accuracy_masked_fill
FlagGems/src/flag_gems/ops/masked_fill.py

**现象1：**
在masked_fill.py中加打印， with flag_gems.use_gems():使用时不会出现打印，flag_gems.masked_fill(inp, mask, value)使用时才会走打印引处
**怀疑原因：**
算子没替换好

**现象2：**
flag_gems.masked_fill(inp, mask, value)使用时，‘line61: value = value.contiguous()’出错
**怀疑原因：**
value一般输入是int，不需要.contiguous()

**Comment by StrongSpoon** [comment]
@GwokHiujin  please take a look. I think we need another kernel to deal with scalar-type value.

**Comment by GwokHiujin** [comment]
> @GwokHiujin please take a look. I think we need another kernel to deal with scalar-type value.

Indeed, PyTorch includes the `aten::masked_fill.Scalar(Tensor self, Tensor mask, Scalar value) -> (Tensor)` operation. I will proceed with this task.

**Comment by Dayrker** [comment]
> > @GwokHiujin please take a look. I think we need another kernel to deal with scalar-type value.
> 
> Indeed, PyTorch includes the `aten::masked_fill.Scalar(Tensor self, Tensor mask, Scalar value) -> (Tensor)` operation. I will proceed with this task.

Get it. Thanks~

**Comment by Dayrker** [comment]
> > @GwokHiujin please take a look. I think we need another kernel to deal with scalar-type value.
> 
> Indeed, PyTorch includes the `aten::masked_fill.Scalar(Tensor self, Tensor mask, Scalar value) -> (Tensor)` operation. I will proceed with this task.

Get it. Thanks~
