### ISSUE TITLE
[Tags: v2.1] Error behavior for 'res_out = flag_gems.native_dropout(inp, p, True)'

### ISSUE THREAD

**Issue by Dayrker** [FlagOpen/FlagGems#267]
### Describe the bug

位置：
FlagGems/tests/test_special_ops.py::test_accuracy_dropout
FlagGems/src/flag_gems/ops/dropout.py
现象：
1. res_out = flag_gems.native_dropout(inp, p, True)使用的时候会报错
mask0 = r0 > p
E                            ^
E           IncompatibleTypeErrorImpl('invalid operands of type pointer<fp32> and triton.language.fp32')

**Comment by StrongSpoon** [comment]
Could you please provide a demo code to recurring this error? 
![截屏2024-10-31 10 07 03](https://github.com/user-attachments/assets/8d04972c-6388-4d49-8b07-4bd2c3bbd05b)

**Comment by Dayrker** [comment]
> Could you please provide a demo code to recurring this error? ![截屏2024-10-31 10 07 03](https://private-user-images.githubusercontent.com/35829812/381797769-8d04972c-6388-4d49-8b07-4bd2c3bbd05b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzgxNjQsIm5iZiI6MTczMDYzNzg2NCwicGF0aCI6Ii8zNTgyOTgxMi8zODE3OTc3NjktOGQwNDk3MmMtNjM4OC00ZDQ5LThiMDctNGJkMmMzYmJkMDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEyNDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMTg2NzU5NGFhODlkOTJjZDZkY2RmOGY5ZGVhMzkwMDFkYTdiYmIyZDE0NTAxYWMyZmZmMzQ5MWE4NGNjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1AyRuqvTlzj0Ko49m1eiOtkHfoto5g3UP5i2UVoSkbg)

change here.
![e30fa463edacd7fdc9a2898f852d4fb](https://github.com/user-attachments/assets/8f1deaac-9b24-4dc6-9e66-d80050b98497)
then use "pytest tests/test_special_ops.py::test_accuracy_dropout"

**Comment by StrongSpoon** [comment]
This is due to the data type of operand p. Triton kernel can't accept p as numpy.float32 directly. Annotate the code "p = np.float32(p)" and this error disappears.

**Comment by Dayrker** [comment]
> This is due to the data type of operand p. Triton kernel can't accept p as numpy.float32 directly. Annotate the code "p = np.float32(p)" and this error disappears.

Get it. Tanhks!
