### ISSUE TITLE
about "transpose" and "permute"

### ISSUE THREAD

**Issue by Shaquille-Wu** [FlagOpen/FlagGems#282]
### Please describe your question

hello, Flag experts:
I've applied FlagOpen into my project
but, I didn't find any ops about "transpose" or "permute" in FlagOpen.
So, how can I solve this trouble?
Is there anyone would like to help me?

**Comment by tongxin** [comment]
The pytorch style tranpose/permute normally returns a view or shares the underlying storage of the input tensor so they don't need a kernel.  If you are referring to tensor transpose with data movement, you probably need a contiguous() or copy_() which are not implemented yet in FlagGems. We're planning on adding them later.

**Comment by Shaquille-Wu** [comment]
thanks your reply
