### ISSUE TITLE
Add filter_shape method to Benchmark class

### ISSUE THREAD

**Issue by Gxiandy** [FlagOpen/FlagGems#284]
### The feature, motivation and pitch

Hi all,
   When writing performance tests for newly added diag op, I found the Benchmark class do not have a method to filter out the input shapes which satisfy the requirement of the testing op (for diag op, it only need 1d and 2d square tensor as input). It will be mush convenient to write tests for such op we have a filter_shape method in Benchmark class

**Comment by tongxin** [comment]
@kiddyjinjin

**Comment by kiddyjinjin** [comment]
Hi there! 
Actually, we already provide filtering capabilities in our project through the `performance_utils.py` file. Specifically, we have defined three classes: `GenericBenchmarkExclude1D`, `GenericBenchmarkExclude3D`, and `GenericBenchmark2DOnly`. These classes allow for filtering out 1D, filtering out 3D, and supporting only 2D shapes, respectively. They all inherit from the common base class `GenericBenchmarkFilterShapes`. If you inherit from this base class, you can gain flexible filtering capabilities for various shape requirements.

For the `diag` operator, which supports only 1D and 2D square shapes, I’d suggest inheriting from `GenericBenchmarkExclude3D` to implement your own benchmark method. Then, in the `set_more_shapes` function, you could add stricter filtering to exclude non-square 2D shapes. You might find it helpful to refer to the implementation of `set_more_shapes` in the `TensorSelectBenchmark` class as an example.

Alternatively, if you want to bypass the default shapes configured in the benchmark setup, you can add shape information specifically for `diag` in the `core_shapes.yaml` file. It should be relatively straightforward to configure, and a quick look at the file will help clarify any details.

Hope this helps!

**Comment by kiddyjinjin** [comment]
@Gxiandy  Let us know if you have any other questions;  otherwise, I'll close this issue.
