### ISSUE TITLE
About performance between ATen and triton

### ISSUE THREAD

**Issue by gavin838** [FlagOpen/FlagGems#285]
### Please describe your question

@tongxin ,
hi, ./assets/speedup-0814-chn.png这个文件里面涉及的用例脚本是否可以上传下，参考下你们用的shape，后面回归也比较方便^_^

**Comment by gavin838** [comment]
是不是就是benchmark下面的那些

**Comment by tongxin** [comment]
@StrongSpoon 麻烦回复一下。

**Comment by StrongSpoon** [comment]
0814使用的是旧版本的测试脚本，形状范围为SIZES = [i * 64 for i in range(1, 22, 5)]，目前在新的benchmark中已经弃用。请提供您的邮箱，我将测试文件发送过去。

**Comment by gavin838** [comment]
> 0814使用的是旧版本的测试脚本，形状范围为SIZES = [i * 64 for i in range(1, 22, 5)]，目前在新的benchmark中已经弃用。请提供您的邮箱，我将测试文件发送过去。

1164998630@qq.com  thx.
