### ISSUE TITLE
masked_fill op bug

### ISSUE THREAD

**Issue by Salv1a** [FlagOpen/FlagGems#299]
### Describe the bug

1. Registration bug. `flag_gems.masked_fill` implementation is not correctly registered for `torch.masked_fill` op. The op names in aTen are `masked_fill_.Tensor`  and `masked_fill_.Scalar`.
2. `flag_gems.masked_fill` has some bugs: 
* Variables in the config mismatch the args in the triton kernel
"TypeError: dynamic_func() missing 2 required positional arguments: 'BLOCK_M' and 'BLOCK_N'"
* `value = value.contiguous()` raises error 
"AttributeError: 'int' object has no attribute 'contiguous"
* When inp is (), `N = inp.size(inp.ndim - 1)` raises error 
"IndexError: Dimension specified as -1 but tensor has no dimensions"

**Comment by GwokHiujin** [comment]
Thank you for raising these bugs!

Regarding the registration bug, the current version of `masked_fill` in the operator plan indeed returns a new tensor. However, I understand that you are looking for an in-place implementation of this operator? In the new PR the in-place function has now been implemented and registered. 

I also appreciate you pointing out the other bugs; we are actively working on fixing them. You can take a look at PR#297 and see if it can solve your problem :)

**Comment by Salv1a** [comment]
> Thank you for raising these bugs!
> 
> Regarding the registration bug, the current version of `masked_fill` in the operator plan indeed returns a new tensor. However, I understand that you are looking for an in-place implementation of this operator? In the new PR the in-place function has now been implemented and registered.
> 
> I also appreciate you pointing out the other bugs; we are actively working on fixing them. You can take a look at PR#297 and see if it can solve your problem :)

Haha, sry, I did not notice that you have been working on this problem. In the bug description above, I made a mistake that the out-of-place implemetion should be registered for `masked_fill.Scalar`. PR#297 LGTM👍.
