### ISSUE TITLE
在跑通『LLaVA单卡+gems』过程总遇到的cat除零bug

### ISSUE THREAD

**Issue by 0x45f** [FlagOpen/FlagGems#302]
### Describe the bug

 cat有除零错误
![image](https://github.com/user-attachments/assets/fae2e72e-dfff-4fb2-a093-53f38be8823a) |

**Comment by iclementine** [comment]
发现了问题了。在 FlagGems 的 pointwise 系列算子的 tile size 计算逻辑中没有考虑到 tensor 的 size 为 0 的问题。
fixing
