### ISSUE TITLE
Code Contribution: 【Lv1】【Operator Development】diagonal_backward

### ISSUE THREAD

**Issue by StrongSpoon** [FlagOpen/FlagGems#314]
## Description 任务介绍
Develop backward function for diagonal operator.
开发diagonal算子的反向功能。
## Requirements 任务要求
__Interface 接口__
`diagonal_backward(Tensor grad_output, SymInt[] input_sizes, int offset, int dim1, int dim2) -> Tensor`
__Function reference 功能参考__
https://pytorch.org/docs/stable/generated/torch.diagonal.html#torch-diagonal
__Implementation reference 实现参考__
https://github.com/FlagOpen/FlagGems/blob/master/src/flag_gems/ops/diag.py

The operator should support all optional arguments defined in the interface. 
算子应支持接口中定义的所有参数选项。
## DDL 提交时间
Please submit a Pull Request within 1 week after accepting the assignment.
请于接取任务一周内提交PR。
Please provide both accuracy test and performance test code.
请同时提供实现正确性测试与性能测试代码。

**Comment by awayzjj** [comment]
确认下这个要实现的是 diagonal 还是 diag 的 backward？diagonal 我看前向还没有实现呢？

**Comment by StrongSpoon** [comment]
the forward function of diagonal is actually a view of input tensor, and it doesn't launch cuda kernel. this issue calls for implementation of diagonal_backward, which could be registered independently into aten library.

**Comment by awayzjj** [comment]
Binary 认领
