### ISSUE TITLE
Code Contribution: 【Lv2】【Operator Development】cummin

### ISSUE THREAD

**Issue by StrongSpoon** [FlagOpen/FlagGems#321]
## Description 任务介绍
Develop forward function for cummin operator.
开发cummin算子的前向功能。
## Requirements 任务要求
__Interface 接口__
`cummin(Tensor self, int dim) -> (Tensor values, Tensor indices)`
__Function reference 功能参考__
https://pytorch.org/docs/stable/generated/torch.cummin.html#torch-cummin
__Implementation reference 实现参考__
https://github.com/FlagOpen/FlagGems/blob/master/src/flag_gems/ops/cumsum.py

The operator should support all optional arguments defined in the interface. 
算子应支持接口中定义的所有参数选项。
## DDL 提交时间
Please submit a Pull Request within 2 weeks after accepting the assignment.
请于接取任务后两周内提交PR。
Please provide both accuracy test and performance test code.
请同时提供实现正确性测试与性能测试代码。

**Comment by awayzjj** [comment]
awayzjj 认领
