### ISSUE TITLE
quantile算子开发遇到bug

### ISSUE THREAD

**Issue by CelysPr** [FlagOpen/FlagGems#341]
### Please describe your question

我在开发quantile算子时遇到了困难。代码在PR #287 中。
我向test_general_reduction_ops.py添加测试用例（接口为test_accuracy_quantile_without_dim 及 test_accuracy_quantile_dim），发现输入张量执行quantile操作的维度大小正好为256时，quantile算子输出异常：

<img width="1076" alt="failure" src="https://github.com/user-attachments/assets/100463b5-487a-4405-9462-ef20f6a15c08">
（图为使用REDUCTION_SMALL_SHAPE作为输入形状时，测试的结果）

维度大小为257或2560（256的倍数？）或4096（256的倍数及2的整数次幂？），测试结果不会出错；且只有test_accuracy_quantile_dim会遇到问题。但我至今无法定位到代码错误，所以把问题写到issue里，希望各位专家方便时可以帮忙溯源。

**Comment by kiddyjinjin** [comment]
这是你的边界条件的计算逻辑考虑的不够全面导致的。
let‘s discuss this in  PR  https://github.com/FlagOpen/FlagGems/pull/287
