### ISSUE TITLE
Flag Gem性能数据

### ISSUE THREAD

**Issue by philipwan** [FlagOpen/FlagGems#51]
如题，想问下FlagGem的性能数据是否可以标识出来呢，像FlagAttention一样。
还请问算子在A10上效果相较于A100如何

**Comment by tongxin** [comment]
谢谢提议，A100的benchmark数据可以考虑增加，A10暂时没有设备

**Comment by tongxin** [comment]
README is updated with perf data. Feel free to take a look.

**Comment by Ghjk94522** [comment]
请问是否有 amd 相关的性能数据

**Comment by Ghjk94522** [comment]
> README is updated with perf data. Feel free to take a look.

请问是否有 amd gpu 相关的性能数据，比如 MI100
