### ISSUE TITLE
where is rms backforwar

### ISSUE THREAD

**Issue by donghucey** [FlagOpen/FlagGems#70]
rms-norm only forward，

class RmsNorm(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, normalized_shape, weight, eps=1e-5):
        logging.debug("GEMS LAYERNORM FORWARD")
        dim = x.ndim - len(normalized_shape)
        M = math.prod(x.shape[:dim])
        N = math.prod(normalized_shape)

        BLOCK_SIZE = triton.next_power_of_2(N)
        x = x.contiguous()
        weight = weight.contiguous()
        y = torch.empty_like(x)

        rms_norm_kernel[M,](y, x, weight, N, 1, N, 1, N, eps, BLOCK_SIZE)
        return y

def rms_norm(x, normalized_shape, weight, eps=1e-5):
    return RmsNorm.apply(x, normalized_shape, weight, eps)

**Comment by StrongSpoon** [comment]
we only implement rms_norm forward now. as rms_norm is registered with dispatch key "CUDA", it's okay to construct the operator as a class. torch autograd still works for it.

**Comment by iclementine** [comment]
In this case, we can implement it as a `torch.autograd.Function`.
