### ISSUE TITLE
Please update the document according to the repository

### ISSUE THREAD

**Issue by RubiaCx** [FlagOpen/FlagGems#86]
请根据仓库的内容和结构实时更新README.md等文档，比如在“执行”一节算子测试的路径和文件已经完全改变了🙏
如果有需要，可以提pr😊

**Comment by RubiaCx** [comment]
在测试时，我的3.0.0版本的Triton报错`AttributeError: module 'triton.language.math' has no attribute 'tanh'`，建议将Triton版本设置一个上界，比如 N >= Triton >= 2.2.0

**Comment by tongxin** [comment]
谢谢你的反馈，欢迎提PR；）

**Comment by StrongSpoon** [comment]
收到反馈，我们尽快更新🫡
